language: python
python:
  - "2.7"
pcache: apt
script:
  - pip install -e .
  - python setup.py test
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
after_success:
  - pip install python-coveralls
  - coveralls
