language: python
python:
  - "2.7"
pcache: apt
script:
  - pip install -e .
  - python setup.py test
before_install:
  - sudo apt-get install thrift-compiler
after_success:
  - pip install python-coveralls
  - coveralls
