language: python
pcache: apt
install:
  - pip install tox
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
script:
  - tox
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
after_success:
  - pip install python-coveralls
  - coveralls
